name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  firebase_core: ^2.25.2
  cloud_firestore: ^4.15.2
  shared_preferences: ^2.2.2
  bubble: ^1.2.1
  intl: ^0.19.0

  
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
