// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxHzhj73PDKtMGmHZ24BJF0tbFvYG_jwY',
    appId: '1:528659814002:web:60955a547a6fa4f9eb94eb',
    messagingSenderId: '528659814002',
    projectId: 'chatapp-f7f9f',
    authDomain: 'chatapp-f7f9f.firebaseapp.com',
    storageBucket: 'chatapp-f7f9f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPUdibY1Tu_w52rna9OxS84qj2xmJdXOc',
    appId: '1:528659814002:android:cd638ed3b452822eeb94eb',
    messagingSenderId: '528659814002',
    projectId: 'chatapp-f7f9f',
    storageBucket: 'chatapp-f7f9f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAreOgkGBKuSHS7na-cOxvJkim6-NE2zLU',
    appId: '1:528659814002:ios:3bfccba1541b437beb94eb',
    messagingSenderId: '528659814002',
    projectId: 'chatapp-f7f9f',
    storageBucket: 'chatapp-f7f9f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAreOgkGBKuSHS7na-cOxvJkim6-NE2zLU',
    appId: '1:528659814002:ios:39bab1445539be1deb94eb',
    messagingSenderId: '528659814002',
    projectId: 'chatapp-f7f9f',
    storageBucket: 'chatapp-f7f9f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
